### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by Steve-deltora** [Kishibe3/non-tracking-google-dictionary#1]
![image](https://github.com/Kishibe3/non-tracking-google-dictionary/assets/54358541/2675bca8-78f9-4ba7-9f4e-5ffd7c593c8e)

**Comment by Kishibe3** [comment]
Sorry for not noticing this issue until now. I had fixed it in 2023/9/19. Please replace popup.js with the newest version. Thank you.
If you still encounter other related issues, feel free to respond me.
Sorry again for not replying for such a long time. (╥﹏╥)
